[package]
name = "fcars"
version = "0.1.0"
edition = "2024"
authors = ["Ben Spitz <diracdeltafunk@users.noreply.github.com>"]

[lib]
name = "fcars"
path = "src/lib.rs"

[dependencies]
bitvec = "1.0.1"
rayon = "1.11.0"
rand = {version = "0.9.2", optional = true}

[features]
random = ["dep:rand"]
